### docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: restaurant_db
    environment:
      POSTGRES_DB: restaurant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: uchiha123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: restaurant_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/restaurant
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: uchiha123
      SPRING_PROFILES_ACTIVE: gd
    ports:
      - "8081:8081"
    restart: on-failure

volumes:
  postgres_data: